# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import index_pb2 as index__pb2


GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in index_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IndexStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.takeNext = channel.unary_unary(
                '/search.Index/takeNext',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=index__pb2.TakeNextResponse.FromString,
                _registered_method=True)
        self.putNew = channel.unary_unary(
                '/search.Index/putNew',
                request_serializer=index__pb2.PutNewRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.addToIndexWords = channel.unary_unary(
                '/search.Index/addToIndexWords',
                request_serializer=index__pb2.AddToIndexRequestWords.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.addToIndexLinks = channel.unary_unary(
                '/search.Index/addToIndexLinks',
                request_serializer=index__pb2.AddToIndexRequestLinks.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.searchWord = channel.unary_unary(
                '/search.Index/searchWord',
                request_serializer=index__pb2.SearchWordRequest.SerializeToString,
                response_deserializer=index__pb2.SearchWordResponse.FromString,
                _registered_method=True)
        self.searchBacklinks = channel.unary_unary(
                '/search.Index/searchBacklinks',
                request_serializer=index__pb2.SearchBacklinksRequest.SerializeToString,
                response_deserializer=index__pb2.SearchBacklinksResponse.FromString,
                _registered_method=True)
        self.getFullIndex = channel.unary_unary(
                '/search.Index/getFullIndex',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=index__pb2.FullIndexResponse.FromString,
                _registered_method=True)
        self.registerIndexBarrel = channel.unary_unary(
                '/search.Index/registerIndexBarrel',
                request_serializer=index__pb2.IndexBarrelRequest.SerializeToString,
                response_deserializer=index__pb2.ValidRegister.FromString,
                _registered_method=True)
        self.getIndexBarrels = channel.unary_unary(
                '/search.Index/getIndexBarrels',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=index__pb2.IndexBarrelInfo.FromString,
                _registered_method=True)
        self.getStats = channel.unary_unary(
                '/search.Index/getStats',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=index__pb2.SystemStats.FromString,
                _registered_method=True)
        self.updateIndexSize = channel.unary_unary(
                '/search.Index/updateIndexSize',
                request_serializer=index__pb2.IndexSizeUpdateRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SendStats = channel.unary_unary(
                '/search.Index/SendStats',
                request_serializer=index__pb2.SystemStats.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.startSendingStatistics = channel.unary_unary(
                '/search.Index/startSendingStatistics',
                request_serializer=index__pb2.WebServerInfo.SerializeToString,
                response_deserializer=index__pb2.SystemStats.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/search.Index/Ping',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class IndexServicer(object):
    """Missing associated documentation comment in .proto file."""

    def takeNext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def putNew(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def addToIndexWords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def addToIndexLinks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def searchWord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def searchBacklinks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getFullIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def registerIndexBarrel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getIndexBarrels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateIndexSize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def startSendingStatistics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IndexServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'takeNext': grpc.unary_unary_rpc_method_handler(
                    servicer.takeNext,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=index__pb2.TakeNextResponse.SerializeToString,
            ),
            'putNew': grpc.unary_unary_rpc_method_handler(
                    servicer.putNew,
                    request_deserializer=index__pb2.PutNewRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'addToIndexWords': grpc.unary_unary_rpc_method_handler(
                    servicer.addToIndexWords,
                    request_deserializer=index__pb2.AddToIndexRequestWords.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'addToIndexLinks': grpc.unary_unary_rpc_method_handler(
                    servicer.addToIndexLinks,
                    request_deserializer=index__pb2.AddToIndexRequestLinks.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'searchWord': grpc.unary_unary_rpc_method_handler(
                    servicer.searchWord,
                    request_deserializer=index__pb2.SearchWordRequest.FromString,
                    response_serializer=index__pb2.SearchWordResponse.SerializeToString,
            ),
            'searchBacklinks': grpc.unary_unary_rpc_method_handler(
                    servicer.searchBacklinks,
                    request_deserializer=index__pb2.SearchBacklinksRequest.FromString,
                    response_serializer=index__pb2.SearchBacklinksResponse.SerializeToString,
            ),
            'getFullIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.getFullIndex,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=index__pb2.FullIndexResponse.SerializeToString,
            ),
            'registerIndexBarrel': grpc.unary_unary_rpc_method_handler(
                    servicer.registerIndexBarrel,
                    request_deserializer=index__pb2.IndexBarrelRequest.FromString,
                    response_serializer=index__pb2.ValidRegister.SerializeToString,
            ),
            'getIndexBarrels': grpc.unary_unary_rpc_method_handler(
                    servicer.getIndexBarrels,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=index__pb2.IndexBarrelInfo.SerializeToString,
            ),
            'getStats': grpc.unary_unary_rpc_method_handler(
                    servicer.getStats,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=index__pb2.SystemStats.SerializeToString,
            ),
            'updateIndexSize': grpc.unary_unary_rpc_method_handler(
                    servicer.updateIndexSize,
                    request_deserializer=index__pb2.IndexSizeUpdateRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SendStats': grpc.unary_unary_rpc_method_handler(
                    servicer.SendStats,
                    request_deserializer=index__pb2.SystemStats.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'startSendingStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.startSendingStatistics,
                    request_deserializer=index__pb2.WebServerInfo.FromString,
                    response_serializer=index__pb2.SystemStats.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'search.Index', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('search.Index', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Index(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def takeNext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.Index/takeNext',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            index__pb2.TakeNextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def putNew(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.Index/putNew',
            index__pb2.PutNewRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def addToIndexWords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.Index/addToIndexWords',
            index__pb2.AddToIndexRequestWords.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def addToIndexLinks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.Index/addToIndexLinks',
            index__pb2.AddToIndexRequestLinks.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def searchWord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.Index/searchWord',
            index__pb2.SearchWordRequest.SerializeToString,
            index__pb2.SearchWordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def searchBacklinks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.Index/searchBacklinks',
            index__pb2.SearchBacklinksRequest.SerializeToString,
            index__pb2.SearchBacklinksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getFullIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.Index/getFullIndex',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            index__pb2.FullIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def registerIndexBarrel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.Index/registerIndexBarrel',
            index__pb2.IndexBarrelRequest.SerializeToString,
            index__pb2.ValidRegister.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getIndexBarrels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.Index/getIndexBarrels',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            index__pb2.IndexBarrelInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.Index/getStats',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            index__pb2.SystemStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updateIndexSize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.Index/updateIndexSize',
            index__pb2.IndexSizeUpdateRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.Index/SendStats',
            index__pb2.SystemStats.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def startSendingStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.Index/startSendingStatistics',
            index__pb2.WebServerInfo.SerializeToString,
            index__pb2.SystemStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.Index/Ping',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
